frr version 8.4
frr defaults traditional
hostname aol_router
log syslog
no ipv6 forwarding

router ospf
 ospf router-id 1.1.1.1
 network 172.16.0.0/16 area 0
 default-information originate
!
line vty
